export const MESSAGES = {
  SUCCESS: 'Successfully',
  CREATED: 'Created successfully',
  DELETED: 'Deleted successfully',
  INVALID_TOKEN: 'Invalid token',
  NOT_FOUND: 'Not found',
  IS_NOT_EMPTY: 'Field cannot be blank',
  INCORRECT_DATA_TYPE: 'Incorrect data type',
  PASSWORD_MIN_LENGTH: 'Password must be at least 6 characters long',
  MIN_SIZE: 'Size must be greater than 0',
  INVALID_PROVIDER: 'Provider must be one of GOOGLE, APPLE, or FACEBOOK',
  INVALID_SUPPORT_TYPE: 'Type must be one of EMAIL, PHONE, or CHAT',
  INVALID_EMAIL: 'Invalid email',
  INVALID_OTP: 'Invalid OTP',
  OTP_EXPIRED: 'OTP expired',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  INVALID_OR_EXPIRED_REFRESH_TOKEN: 'Refresh token expired or invalid',
  INVALID_EMAIL_PASSWORD: 'Invalid email or password',
  TOO_MANY_REQUESTS: 'Too many requests. Please wait 60 seconds.',
  INVALID_EMAIL_CLIENT: 'Invalid Email or Client',
  EMAIL_REQUIRED: 'Email are required',
  USER_NOT_FOUND: 'User not found',
  SUPPORT_NOT_FOUND: 'Support not found',
  LOCK_DISABLE: 'lock command has been disabled',
  DEVICE_LOCKED_BY_USER: 'This device is locked',
  LOCK_ID_NOT_FOUND: 'Lock ID not found',
  LOCK_ERROR: 'Lock error',
  ACTIVITIES_NOT_FOUND: 'Activities not found',
  VOLUME_NOT_FOUND: 'Volume not found',
  YUBIKEY_REGISTERED: 'Yubikey already registered',
  INVALID_YUBICO_RESPONSE: 'Invalid Yubico response',
  YUBIKEY_REGISTERED_FAILED: 'Yubikey registration failed',
  CHALLENGE_NOT_FOUND: 'Challenge expired or not found',
  YUBIKEY_VERIFY_FAILED: 'Yubikey verification failed: ',
  YUBIKEY_REGISTER_FAILED: 'YubiKey register failed: ',
  INVALID_OTP_FORMAT: 'Invalid OTP format',
  YUBIKEY_NOT_REGISTER_FOR_VOLUME:
    'Yubikey device not registered for this volume',
  AUTHENTICATION_FAILED: 'Authentication failed',
  NO_PASSKEY_REGISTERED: 'No passkey registered for this volume',
  DEVICE_NOT_FOUND: 'Device not found',
  RESET_TOKEN_IS_REQUIRED: 'Reset token is required',
  INVALID_EXPIRED_RESET_TOKEN: 'Invalid or expired reset token',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  INVALID_ENCRYPTED_TEXT: 'Invalid encrypted text format',
  TOKEN_REVOKED: 'Token has been revoked',
  DEVICE_ALREADY_EXISTS: 'Device already exists',
  SECRET_KEY_LENGTH_32: 'Secret key must be exactly 32 characters long.',
  PERMISSION_DENIED_ADMIN: 'Permission denied: only ADMIN can login.',
  NOT_FOUND_USER_GUEST: 'Not found user guest',
  ACCESS_DENIED_IP: 'Access denied from IP:',
  DEVICE_LOCKED: 'This device is locked',
  USER_LOCKED:
    'This user is locked.' + ' Please contact support to use the service',
  UNABLE_CREATE_VOLUMES: 'Unable to create volume',
  FAILED_LOGIN_GUEST: 'Failed to login as guest',
  DB_CONNECTION_FAILED: 'Database connection failed',
  USER_CHANGE_STATE: 'User is in request state please change to another state',
  LIMIT_FILE_UPLOAD: 'File size exceeds 1MB',
  NO_FILE_PROVIDED: 'No file provided',
  ACTIVITY_NOT_FOUND: 'Activity not found',
};

export enum algorithmName {
  AES_256_GCM = 'aes-256-gcm',
  UTF8 = 'utf8',
  BASE64 = 'base64',
  SHA1 = 'sha1',
}

export const IMAGE_TYPE = 'image';
export const ICON_TYPE = 'icon';
export const DATA_NAME = 'data';
export const MULTIPART = 'multipart/form-data';
export const SUPPORT_ICON_LINK = 'support-icons';
